/*
 * This file is generated by jOOQ.
*/
package cn.exercise.demo.pojo.po;


import cn.exercise.demo.pojo.po.tables.UserInfo;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ExerciseTest extends SchemaImpl {

    private static final long serialVersionUID = 1835918639;

    /**
     * The reference instance of <code>exercise_test</code>
     */
    public static final ExerciseTest EXERCISE_TEST = new ExerciseTest();

    /**
     * The table <code>exercise_test.user_info</code>.
     */
    public final UserInfo USER_INFO = cn.exercise.demo.pojo.po.tables.UserInfo.USER_INFO;

    /**
     * No further instances allowed
     */
    private ExerciseTest() {
        super("exercise_test", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            UserInfo.USER_INFO);
    }
}
