/*
 * This file is generated by jOOQ.
*/
package cn.exercise.demo.pojo.po;


import cn.exercise.demo.pojo.po.tables.UserInfo;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>exercise_test</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index USER_INFO_PRIMARY = Indexes0.USER_INFO_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index USER_INFO_PRIMARY = Internal.createIndex("PRIMARY", UserInfo.USER_INFO, new OrderField[] { UserInfo.USER_INFO.ID }, true);
    }
}
