/*
 * This file is generated by jOOQ.
*/
package cn.exercise.demo.pojo.po;


import cn.exercise.demo.pojo.po.tables.UserInfo;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in exercise_test
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>exercise_test.user_info</code>.
     */
    public static final UserInfo USER_INFO = cn.exercise.demo.pojo.po.tables.UserInfo.USER_INFO;
}
