/*
 * This file is generated by jOOQ.
 */
package cn.aimasa.hetongfenglei.pojo.po;


import cn.aimasa.hetongfenglei.pojo.po.tables.File;
import cn.aimasa.hetongfenglei.pojo.po.tables.FlywaySchemaHistory;
import cn.aimasa.hetongfenglei.pojo.po.tables.User;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClassfiyContact extends SchemaImpl {

    private static final long serialVersionUID = -1894043554;

    /**
     * The reference instance of <code>classfiy_contact</code>
     */
    public static final ClassfiyContact CLASSFIY_CONTACT = new ClassfiyContact();

    /**
     * The table <code>classfiy_contact.file</code>.
     */
    public final File FILE = File.FILE;

    /**
     * The table <code>classfiy_contact.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>classfiy_contact.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private ClassfiyContact() {
        super("classfiy_contact", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            File.FILE,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            User.USER);
    }
}
