/*
 * This file is generated by jOOQ.
 */
package cn.aimasa.hetongfenglei.pojo.po;


import java.util.Arrays;
import java.util.List;

import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DefaultCatalog extends CatalogImpl {

    private static final long serialVersionUID = 875136346;

    /**
     * The reference instance of <code>DEFAULT_CATALOG</code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     * The schema <code>classfiy_contact</code>.
     */
    public final ClassfiyContact CLASSFIY_CONTACT = ClassfiyContact.CLASSFIY_CONTACT;

    /**
     * No further instances allowed
     */
    private DefaultCatalog() {
        super("");
    }

    @Override
    public final List<Schema> getSchemas() {
        return Arrays.<Schema>asList(
            ClassfiyContact.CLASSFIY_CONTACT);
    }
}
