/*
 * This file is generated by jOOQ.
 */
package cn.aimasa.hetongfenglei.pojo.po;


import cn.aimasa.hetongfenglei.pojo.po.tables.File;
import cn.aimasa.hetongfenglei.pojo.po.tables.FlywaySchemaHistory;
import cn.aimasa.hetongfenglei.pojo.po.tables.User;


/**
 * Convenience access to all tables in classfiy_contact
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>classfiy_contact.file</code>.
     */
    public static final File FILE = File.FILE;

    /**
     * The table <code>classfiy_contact.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>classfiy_contact.user</code>.
     */
    public static final User USER = User.USER;
}
