/*
 * This file is generated by jOOQ.
 */
package cn.aimasa.hetongfenglei.pojo.po.tables.records;


import cn.aimasa.hetongfenglei.pojo.po.tables.File;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FileRecord extends UpdatableRecordImpl<FileRecord> implements Record5<Integer, Integer, byte[], String, String> {

    private static final long serialVersionUID = 1810514006;

    /**
     * Setter for <code>classfiy_contact.file.id</code>. 文件id
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>classfiy_contact.file.id</code>. 文件id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>classfiy_contact.file.userid</code>. 上传文件者id
     */
    public void setUserid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>classfiy_contact.file.userid</code>. 上传文件者id
     */
    public Integer getUserid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>classfiy_contact.file.content</code>. 二进制文件
     */
    public void setContent(byte[] value) {
        set(2, value);
    }

    /**
     * Getter for <code>classfiy_contact.file.content</code>. 二进制文件
     */
    public byte[] getContent() {
        return (byte[]) get(2);
    }

    /**
     * Setter for <code>classfiy_contact.file.classfiy_field</code>. 文件类别
0 - 租赁合同
1 -  买卖合同
2 - 劳动合同
     */
    public void setClassfiyField(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>classfiy_contact.file.classfiy_field</code>. 文件类别
0 - 租赁合同
1 -  买卖合同
2 - 劳动合同
     */
    public String getClassfiyField() {
        return (String) get(3);
    }

    /**
     * Setter for <code>classfiy_contact.file.filename</code>. 文件名字
     */
    public void setFilename(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>classfiy_contact.file.filename</code>. 文件名字
     */
    public String getFilename() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Integer, Integer, byte[], String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Integer, Integer, byte[], String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return File.FILE.ID;
    }

    @Override
    public Field<Integer> field2() {
        return File.FILE.USERID;
    }

    @Override
    public Field<byte[]> field3() {
        return File.FILE.CONTENT;
    }

    @Override
    public Field<String> field4() {
        return File.FILE.CLASSFIY_FIELD;
    }

    @Override
    public Field<String> field5() {
        return File.FILE.FILENAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUserid();
    }

    @Override
    public byte[] component3() {
        return getContent();
    }

    @Override
    public String component4() {
        return getClassfiyField();
    }

    @Override
    public String component5() {
        return getFilename();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUserid();
    }

    @Override
    public byte[] value3() {
        return getContent();
    }

    @Override
    public String value4() {
        return getClassfiyField();
    }

    @Override
    public String value5() {
        return getFilename();
    }

    @Override
    public FileRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public FileRecord value2(Integer value) {
        setUserid(value);
        return this;
    }

    @Override
    public FileRecord value3(byte[] value) {
        setContent(value);
        return this;
    }

    @Override
    public FileRecord value4(String value) {
        setClassfiyField(value);
        return this;
    }

    @Override
    public FileRecord value5(String value) {
        setFilename(value);
        return this;
    }

    @Override
    public FileRecord values(Integer value1, Integer value2, byte[] value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FileRecord
     */
    public FileRecord() {
        super(File.FILE);
    }

    /**
     * Create a detached, initialised FileRecord
     */
    public FileRecord(Integer id, Integer userid, byte[] content, String classfiyField, String filename) {
        super(File.FILE);

        set(0, id);
        set(1, userid);
        set(2, content);
        set(3, classfiyField);
        set(4, filename);
    }
}
