/*
 * This file is generated by jOOQ.
 */
package cn.aimasa.hetongfenglei.pojo.po.tables.records;


import cn.aimasa.hetongfenglei.pojo.po.tables.User;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record2<Integer, Integer> {

    private static final long serialVersionUID = 487686497;

    /**
     * Setter for <code>classfiy_contact.user.id</code>. 用户id
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>classfiy_contact.user.id</code>. 用户id
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>classfiy_contact.user.user_name</code>. 用户名
     */
    public void setUserName(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>classfiy_contact.user.user_name</code>. 用户名
     */
    public Integer getUserName() {
        return (Integer) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row2<Integer, Integer> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    @Override
    public Row2<Integer, Integer> valuesRow() {
        return (Row2) super.valuesRow();
    }

    @Override
    public Field<Integer> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<Integer> field2() {
        return User.USER.USER_NAME;
    }

    @Override
    public Integer component1() {
        return getId();
    }

    @Override
    public Integer component2() {
        return getUserName();
    }

    @Override
    public Integer value1() {
        return getId();
    }

    @Override
    public Integer value2() {
        return getUserName();
    }

    @Override
    public UserRecord value1(Integer value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(Integer value) {
        setUserName(value);
        return this;
    }

    @Override
    public UserRecord values(Integer value1, Integer value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Integer id, Integer userName) {
        super(User.USER);

        set(0, id);
        set(1, userName);
    }
}
