/*
 * This file is generated by jOOQ.
 */
package cn.aimasa.hetongfenglei.pojo.po.tables.pojos;


import java.io.Serializable;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 986258436;

    private Integer id;
    private Integer userName;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.userName = value.userName;
    }

    public User(
        Integer id,
        Integer userName
    ) {
        this.id = id;
        this.userName = userName;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserName() {
        return this.userName;
    }

    public void setUserName(Integer userName) {
        this.userName = userName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(userName);

        sb.append(")");
        return sb.toString();
    }
}
