/*
 * This file is generated by jOOQ.
*/
package cn.exercise.demo.pojo.po.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserInfo implements Serializable {

    private static final long serialVersionUID = -311701396;

    private Integer id;
    private String  userName;
    private String  sex;
    private Integer age;

    public UserInfo() {}

    public UserInfo(UserInfo value) {
        this.id = value.id;
        this.userName = value.userName;
        this.sex = value.sex;
        this.age = value.age;
    }

    public UserInfo(
        Integer id,
        String  userName,
        String  sex,
        Integer age
    ) {
        this.id = id;
        this.userName = userName;
        this.sex = sex;
        this.age = age;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getSex() {
        return this.sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("UserInfo (");

        sb.append(id);
        sb.append(", ").append(userName);
        sb.append(", ").append(sex);
        sb.append(", ").append(age);

        sb.append(")");
        return sb.toString();
    }
}
